server:
  port: 8888
  
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=GMT&useSSL=false
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
     
mybatis:
  mapper-locations: classpath:pers/song/demo/mapper/*.xml